sonar.projectKey=ottbackendv01
sonar.projectName=ottbackendv01
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts

# Point to actual test files
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# JVM memory fix for scanner
sonar.scanner.javaOpts=-Xmx2048m -Xms512m
